name: Deploy ASP.NET Core API to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o C:\deploy\HrmsApi

      - name: Stop App Pool
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "HrmsApiAppPool"

      - name: Deploy Files
        run: robocopy C:\deploy\HrmsApi C:\inetpub\wwwroot\api\HrmsApi /MIR

      - name: Start App Pool
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "HrmsApiAppPool"