name: Deploy ASP.NET Core API to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o C:\Publish\HrmsApi

      - name: Deploy Files
        run: robocopy C:\Publish\HrmsApi C:\inetpub\wwwroot\api\HrmsApi /MIR

      - name: Restart App Pool
        shell: powershell
        run: |
          & "$env:windir\system32\inetsrv\appcmd.exe" stop apppool /apppool.name:"HrmsApi"
          & "$env:windir\system32\inetsrv\appcmd.exe" start apppool /apppool.name:"HrmsApi"